//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegatubeDataMigrator.ModelNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FilenName { get; set; }
        public System.DateTime UploadDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public int DataId { get; set; }
    
        public virtual BinaryData BinaryData { get; set; }
        public virtual User User { get; set; }
    }
}
