//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegatubeDataMigrator.ModelNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewChannel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public double PercentMegatube { get; set; }
        public double PercentOwner { get; set; }
        public double PercentRecruiter { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> RecruiterId { get; set; }
        public string RecruiterName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LatestActivity { get; set; }
    }
}
