//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegatubeDataMigrator.ModelOld
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelRecruiting
    {
        public string ChannelId { get; set; }
        public int RecruiterId { get; set; }
        public double PercentRecruiter { get; set; }
        public System.DateTime DateRecruiting { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
