//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegatubeDataMigrator.ModelOld
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelReport
    {
        public string ChannelId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public decimal TotalEarningsInDollar { get; set; }
        public decimal TotalEarningsInEuro { get; set; }
        public double DollarToEuroChange { get; set; }
        public decimal PartnerEarningsInEuro { get; set; }
        public decimal RecruiterEarningsInEuro { get; set; }
        public decimal MegatubeEarningsInEuro { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
