//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegatubeDataMigrator.ModelOld
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelOwnership
    {
        public string ChannelId { get; set; }
        public int PartnerId { get; set; }
        public double PercentPartner { get; set; }
        public System.DateTime DateOwnership { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
