//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegatubeDataMigrator.ModelOld
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegatubeEntitiesOld : DbContext
    {
        public MegatubeEntitiesOld()
            : base("name=MegatubeEntitiesOld")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accreditation> Accreditations { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<ChannelOwnership> ChannelOwnerships { get; set; }
        public virtual DbSet<ChannelRecruiting> ChannelRecruitings { get; set; }
        public virtual DbSet<ChannelReport> ChannelReports { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<CustomOwner> CustomOwners { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Network> Networks { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Recruiter> Recruiters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserMontlyEarning> UserMontlyEarnings { get; set; }
        public virtual DbSet<UserPendingRegistration> UserPendingRegistrations { get; set; }
    }
}
