//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegatubeV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNote
    {
        public int Id { get; set; }
        public int Subject { get; set; }
        public int Author { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public string AuthorName { get; set; }
        public string SubjectName { get; set; }
    }
}
