//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegatubeV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewChannelBalance
    {
        public string ChannelId { get; set; }
        public string Name { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> RecruiterId { get; set; }
        public string RecruiterName { get; set; }
        public Nullable<int> Year { get; set; }
        public decimal Jan { get; set; }
        public decimal Feb { get; set; }
        public decimal Mar { get; set; }
        public decimal Apr { get; set; }
        public decimal May { get; set; }
        public decimal Jun { get; set; }
        public decimal Jul { get; set; }
        public decimal Aug { get; set; }
        public decimal Sep { get; set; }
        public decimal Oct { get; set; }
        public decimal Nov { get; set; }
        public decimal Dec { get; set; }
        public decimal TotalYearEarnings { get; set; }
        public double PercentOwner { get; set; }
        public double PercentRecruiter { get; set; }
        public double PercentMegatube { get; set; }
        public int NetworkId { get; set; }
    }
}
